### PR TITLE
Makefile cleanup & add LDFLAGS and CPPFLAGS

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by twinaphex** [comment]
Why don't we use CXXFLAGS btw? Why CPPFLAGS? Any reason for Debian changing this?

**Comment by sergiobenrocha2** [comment]
CPPFLAGS is for the preprocessor

http://stackoverflow.com/questions/495598/difference-between-cppflags-and-cxxflags-in-gnu-make

```
dpkg-buildflags --get CPPFLAGS
-D_FORTIFY_SOURCE=2

dpkg-buildflags --get CXXFLAGS
-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security
```

**Comment by joolswills** [comment]
This breaks snes9x on the RPI3 on Linux - https://github.com/libretro/snes9x/issues/61

**Comment by sergiobenrocha2** [comment]
What commit exactly breaks it? Could you point it?

**Comment by joolswills** [comment]
I put the details in the issue I opened.

**Pull request merged**
