### PR TITLE
Silence warnings about multi-line comments.

### PR DESCRIPTION
**Pull request by orbea**
This will silence the following warnings.

http://pastebin.com/5C9WLUu8

### CODE REVIEW

**Comment by Alcaro** [comment]
Are you sure about that first half?

Personally I'd remove all the //s, not just the first one (or slap on -Wno-comment - I consider this a GCC bug), but this works too.

**Comment by orbea** [comment]
The first half didn't seem to cause any warnings, but I figured I might as well.... I changed the commit to match the style used by mesa as seen here, do you think this is better? 
https://github.com/mesa3d/mesa/blob/7c16552f8dcc869b14cf7ef443a1b5de83b07973/src/mesa/main/api_validate.c#L487

**Comment by Alcaro** [comment]
Well, you did as I said... but the goal of that commented-out macro seems to be being easy to uncomment, and those asterisks don't accomplish that. They're good for making textual comments look nice, but that's not normal text.

As for the first one, if it ain't broke, don't fix it.

**Comment by orbea** [comment]
Fair enough, is this better?

**Pull request merged**
