### PR TITLE
Add "Extreme" option to cycle overclock setting

### PR DESCRIPTION
**Pull request by Electricstar**
"Extreme" option would change cycles to 1/1/1, giving an effective clock speed of 21 MHz, which is the CPU clock speed before any division happens. Could completely eliminate slowdown in games that may somehow still have it at "Max" setting.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
This seems overkill.
What other game than Gradius 3 still has slowdowns (in some rare spots)? 
It doesn't need to go this high and most games will crash.

**Comment by fr500** [comment]
This core is upstream frinedly and I think upstream already said no

**Comment by fr500** [comment]
https://github.com/libretro/snes9x/issues/195#issuecomment-450761347

**Comment by fr500** [comment]
Furthermore I properly rebased this fork a few hours ago so this PR has lots of conflicts...
Sorry about that.

**Comment by twinaphex** [comment]
I can properly backport his last commit, which seems to only touch libretro.c.

I don't think this is something where upstream really is affected, since it only touches libretro.c. It could be a nice option to have for the few games that need it.

Let me just think of a way to cleanly do this without merging this.

**Comment by twinaphex** [comment]
Are there games where there is a measurable difference @Electricstar ?

Also, I think the other PR would be more likely to being merged. But are there games that actually benefit from this or have you not been able to test this beforehand?

**Comment by hizzlekizzle** [comment]
Gonna close this for now. We can revisit later, if needed.

**Pull request closed without merging**
