### PR TITLE
backport ppu fix, libretro cleanup, remove rom headers

### PR DESCRIPTION
**Pull request by kps501**
Fix Umihara Kawase's brightness fluctuation.
tighter upstream sync
remove rom headers

### CODE REVIEW

**Comment by kps501** [comment]
Header roms should get trimmed now, even bios. Sufami Turbo multi-hack roms (+header) also should be okay now, even with 2x multi-link.

Undecided when to include bearoso's irq diverting since it's still in testing. Or if possible to custom hack it in for DBZ:SB2.

And just shoved more things out of core to match upstream better.

**Comment by kps501** [comment]
Don't know who figured out how to backport zsnes cubic, 8-tap interpolation but they both appear to work. Didn't see any zsnes low-pass stuff included though.

**Comment by Tatsuya79** [comment]
Some warnings:
```cpp
../libretro/libretro.cpp: In function 'bool LoadBIOS(uint8*, const char*, int)':
../libretro/libretro.cpp:835:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(size == biossize) r = true;
          ~~~~~^~~~~~~~~~~
../libretro/libretro.cpp: In function 'bool retro_load_game_special(unsigned int, const retro_game_info*, size_t)':
../libretro/libretro.cpp:976:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for(int lcv=0; lcv<num_info; lcv++)
                   ~~~^~~~~~~~~
../libretro/libretro.cpp: In function 'int snes_interp(void*)':
../libretro/libretro.cpp:1728:8: warning: 'output' may be used uninitialized in this function [-Wmaybe-uninitialized]
    int output;
        ^~~~~~
```
And it fails to build with:
```cpp
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x5cb): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x7c8): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0xc8e): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0xed1): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x1114): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x1359): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x159c): undefined reference to `SNES::get_snes_interp()'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x17df): more undefined references to `SNES::get_snes_interp()' follow
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2df7): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2e04): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2e14): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2e24): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2e34): undefined reference to `SNES::snes_interp(void*)'
../apu/bapu/dsp/sdsp.o:sdsp.cpp:(.text+0x2e44): more undefined references to `SNES::snes_interp(void*)' follow
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:524: snes9x_libretro.dll] Error 1
```

**Comment by kps501** [comment]
Have no idea what the compiler error means (okay with msvc) but gave it another shot.

**Comment by kps501** [comment]
Crumbs. That failed to build this time with AppVeyor. Huh.

**Comment by kps501** [comment]
This might not work either, because I don't know what I'm doing like usual. But moreso this time.

**Comment by Tatsuya79** [comment]
It compiled fine this time!
Just this warning remaining:
```cpp
../libretro/libretro.cpp: In function 'bool LoadBIOS(uint8*, const char*, size_t)':
../libretro/libretro.cpp:827:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(ftell(fp)-0x200 == biossize)
          ~~~~~~~~~~~~~~~~^~~~~~~~~~~
```
When changing the sound interpolation core option 8-tap and linear crash the core.

**Comment by Tatsuya79** [comment]
Cubic, none and gaussian seemed OK.
This time linear worked 1st time, then crashed when I came back to it again.
Nothing special in the log. 
I tried without run_ahead that I forgot to switch off, but that's the same.

**Comment by kps501** [comment]
Guessing it happens with any game? Tried several but no faults yet. Linear is simple math so surprised it crashes.

**Comment by kps501** [comment]
Good news is tried some alternate ideas and now it hang crashes on me also (8-tap). Debugging..

**Comment by kps501** [comment]
Thanks for all that testing! I think this should be good and safe now.

**Comment by Tatsuya79** [comment]
Thanks for fixing all that! Works fine now!

What was the default before, gaussian right?
Cubic and 8-tap are interesting, they smoothen the distortion while keeping the higher notes really clear.

**Comment by hizzlekizzle** [comment]
if you want to test auto interpolation, Squaresoft wind is a good one ;)

**Comment by mudlord** [comment]
Question:

Why are you using that monstrous LUT?

http://rebote.net/random/SPC_DSP.cpp

does it much smaller.

**Comment by kps501** [comment]
That's easy. Because I've never seen that before (or any sinc, cubic outside of Zsnes). Thanks! Will use your tables/math instead and put a credits tag.

**Comment by Tatsuya79** [comment]
Cool, sounds the same as before for me.
I should say, I've compared the filters in real time now and I can hear a difference between all of them except for cubic and sinc (or 8-tap, it was similar).
Perhaps it's more substantial with higher quality like MSU, I didn't have some for testing.

Forgot to say I tried "hacked" old goodrom sufami and they work as intended now (similar to what happen upstream).

**Comment by mudlord** [comment]
> Cool, sounds the same as before for me
Excellent.

**Comment by retro-wertz** [comment]
i was expecting Yukari Yoshida voice to sound better but not really.
none and linear doesnt sound right... listen to tales of phantasia intro, the part after the dialogue but before the portion when cymbals starts. cant find any online sound samples thats similar to this.
gaussian - (ok this is snes9x's default, or an actual near hardware sound perfection?)
cubic - not sure what to expect on this, but sounds like no interpolation at all. all high notes are now harshier(is that a word?) maybe a bit finetuning for high notes needed(meaning a bit more interpolation here without making it sounding dull)? but really how is this suppose to sound?
8-tap - not tested. crashes!
anyways why do we need many interpolation anyways? switching between interpolation options also crashes

**Comment by Tatsuya79** [comment]
@retro-wertz You're probably not on the latest version of that PR: the crashes should be fixed and "8-tap" was replaced by "sinc" which sounds similar.

Cubic/sinc sound less muffled than gaussian, they don't lower the high end of the spectrum while fixing the distortion and crackles you can hear without filter.

**Comment by kps501** [comment]
Have you tried the recent mudlord code? That changed a lot of math. 8-tap is now labeled sinc. Otherwise idk. I like having options, even stupid ones. But if they all don't work or are frankly pointless or not worth it, I'll just scrap everything or make it all hidden by using a secret config developer file.

Doing a terrible job of patching things anyway. Probably stop after this one.

**Comment by Tatsuya79** [comment]
No, that's appreciated, and I like the new options! 
Keep them, it's optional and fine!

**Comment by retro-wertz** [comment]
thats what i mean, without a good reference what cubic/sinc should actually sound? for me, its like snes without filtering. ok let me check the merge branch then...

**Comment by Tatsuya79** [comment]
In which game do you hear missing channels?

**Pull request merged**
