### PR TITLE
Silence some warnings

### PR DESCRIPTION
**Pull request by orbea**
This silence a few warnings.

Build log before - http://pastebin.com/z1t7GqTu
Build log after - http://pastebin.com/v5N79byW

### CODE REVIEW

**Comment by Alcaro** [comment]
> \-	ignore = fwrite(Movie.InputBuffer, 1, Movie.BytesPerSample * (Movie.MaxSample + 1), Movie.File);

Dude what the hell, you can't just remove fwrite calls, fwrite has side effects. Don't mess with code you don't understand. Yes, GCC is a whiny bitch, that's not an excuse.

I've got `template<typename T> static inline void ignore(T t) {}` in my programs. Copypaste that and pass the fwrite results there instead.

> -//#define DRAW_PIXEL_H2x1(N, M) \
> -//    if (Z1 > GFX.DB[Offset + 2 * N] && (M)) \
> +//#define DRAW_PIXEL_H2x1(N, M) /
> +//    if (Z1 > GFX.DB[Offset + 2 * N] && (M)) /

And that's not even remotely how things work either; it's called macro and commented-out code, the backslashes belong there. Those warnings are a GCC bug, it shouldn't whine about // [...] \ if the next line also starts with //.

If you want to silence those, remove the //s and replace with /* or #if 0, report the bug upstream, or add -Wno-comments.

**Comment by twinaphex** [comment]
Did it in a better way by just removing the movie code.

**Comment by orbea** [comment]
Well, on one hand I am being told to try to fix things myself while on the other I am being told to not mess with code I don't understand. Both are right, but as it is there is no good way for me to learn without making some mistakes too. That is why this was a pull request so that anything stupid I did could be pointed out before it was potentially merged. :)

Also, thanks twinaphex!

**Comment by twinaphex** [comment]
Well @Alcaro was just concerned I guess about the potential side effects your changes could entail were they to be carelessly merged. 

In any case I do encourage people learning as they go, and there were some good ideas in your PR that I simply rebased a bit.

**Pull request closed without merging**
