### PR TITLE
Use disabled/enabled in the core settings, see libretro/bsnes-mercury#15

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
This will break these options(make all layers impossible to turn off) since they are tested by checking if there first letter is an "N".
`if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value && var.value[0]=='N') disabled_layers|=1<<i;`

**Comment by sergiobenrocha2** [comment]
=='disabled'  instead 'N' will work?

**Comment by twinaphex** [comment]
@meepingsnesroms Please rewrite whatever you did then, that is incredibly messy and honestly that shouldn't be the case at all.

**Comment by meepingsnesroms** [comment]
Its not my fault,I did not write that part,I was just pointing out that it would break it.

**Comment by twinaphex** [comment]
OK then, sorry about that.

Either way, it should be fixed. So let's try to do that.

**Comment by fr500** [comment]
instead of arguing we can change it to use strcmp...
heck I'll do it...

Just wait a few hours for me to get home

**Comment by fr500** [comment]
I'll merge and fix it

**Pull request merged**
