### PR TITLE
libretro blargg filter

### PR DESCRIPTION
**Pull request by stellarporter**
fix pixel_format selection

### CODE REVIEW

**Comment by stellarporter** [comment]
Important: you must do this PR first before compiling this one for emscripten.
https://github.com/libretro/RetroArch/pull/8522

Problem is that Retroarch and snes9x both contain same snes_ntsc.c code. Global variables and functions create grief for emscripten compiler.

1. Retroarch + PR
2. snes9x + PR
3. Emscripten compiler log
https://ci.appveyor.com/project/stellarporter/snes9x/builds/23311319

**Comment by hhromic** [comment]
> Important: you must do this PR first before adding this into snes9x core.
> [libretro/RetroArch#8522](https://github.com/libretro/RetroArch/pull/8522)
> 
> Problem is that Retroarch and snes9x both contain same snes_ntsc.c code. Multiple global variables and functions create grief for emscripten compiler.
> 
> 1. Retroarch + PR
> 2. snes9x + PR
> 3. Emscripten compiler log
>    https://ci.appveyor.com/project/stellarporter/snes9x/builds/23311319

Looks like this PR would break this core for any current RetroArch stable until a new stable with the mentioned PR is released then?

**Comment by stellarporter** [comment]
All compiled cores should work on previous Retroarch executables. It's building the core (emscripten platform only) that requires latest Retroarch github source code to pass.

**Comment by hhromic** [comment]
Ah! sorry I didn't read clearly that you meant emscripten only. That makes sense :)

**Comment by stellarporter** [comment]
Screwed Android again.

**Pull request closed without merging**
