### PR TITLE
hermite_resampler.h: cosmetic - change tabs to spaces to match surrounding code

### PR DESCRIPTION
**Pull request by Dwedit**
Just a minor cosmetic change to hermite_resampler.h to change the tabs into spaces

### CODE REVIEW

**Comment by twinaphex** [comment]
@Dwedit If you happen to notice any of your runahead speed improvements that have come undone as a result of the past couple of PRs we merged, do not hesitate to let me know. I want runahead to be as good as it can be, so if something got undone, know that it was not done intentionally and that I would love to get it again.

**Comment by kps501** [comment]
I'd say look at redoing this one: "11% performance boost on x64 by reducing branches". Upstream blew out lots of irq stuff and S9xCheckInterrupts no longer exists. Will continue checking history on other files.

**Comment by Dwedit** [comment]
Just want to mention that the BS-X code is out of sync with the new snes9x release.

**Comment by kps501** [comment]
Yup. Wanted to do bs-x together with multi-carts since they're more interlinked. Hopefully it'll work out. Of course, I wouldn't mind if someone else does it first.

**Pull request merged**
