### PR TITLE
force libretro settings

### PR DESCRIPTION
**Pull request by kps501**
sound, video, misc

### CODE REVIEW

**Comment by kps501** [comment]
Should apply override sound settings on bootup and load state.

Q: Someone pointed out that snes gaussian suffers the somewhat known brr overflow glitch. Where values switch signs on overflow instead of clamp, creating pops in games (Super Aleste, Super Metroid, Plok, UFO, handful of others). Can be easily detected on high quality sound systems (supposedly).

That's easy to fix but would require another sound option: gaussian (snes) vs gaussian (fixed). Worth it to anyone else?

Also worth noting is that I'm thinking of creating custom 8-tap filters (2048 or 4096 points) which will load from a file, so won't be core included by default. May keep it a hidden feature.

**Comment by Ryunam** [comment]
It would be definitely great to have a Gaussian (fixed) option that prevents any pops from ever occurring.

**Comment by retro-wertz** [comment]
whichever is what or near a real hardware should be like. and just enhance the new interpolation options as need.

As a suggestion, wonder if these filters can be added to main retroarch also if these are not there already, so cores can just output raw audio(therefor speedup performance) and let frontend deal with interpolation and/or resampling. 

just a suggestion

**Comment by Tatsuya79** [comment]
Huh, it completely messes up run_ahead, updating variables each time you push a button or direction.
That can't be done like that.

I can't hear a difference between the 2 gaussian modes on monitor speakers in Super Aleste sound test mode, while I can hear the difference between cubic and sinc on voices there.
Any precise test scenario for that? (if it's about fixing "clicks" I don't think anyone wants them?)

@retro-wertz Mudlord was saying this processing needs to be done at emulator level before output.
So that can't be done as post process like a retroarch dsp filter.

**Comment by Tatsuya79** [comment]
Thanks, run ahead is fine now.

Can't hear anything between them in Plok as well... perhaps that's in an high frequency range my ears can get or something.
I would keep the gaussian that is supposedly fixed only imo.

**Comment by retro-wertz** [comment]
i know my opinion dont matter anyways.. but as ive said earlier, keep whats
suppose to near at or what the hardware sounded like. not everyone wants
hacks and whatnot stuff...but then, this is retroarch anyways...

**Comment by hizzlekizzle** [comment]
Yeah, for the close-to-upstream cores, we typically don't want the default behavior to stray from standalone/upstream, as we get a lot of "why is this different?" bug reports.

This isn't the case with the year-stamped forks, though, so we typically put hacks, fixes, etc into those cores instead.

**Comment by Tatsuya79** [comment]
Guess you can merge it like than then, was just giving my feeling (and wondering it there's a difference at all, if RA isn't doing its own thing that would give a different result).

**Comment by kps501** [comment]
It's decided! Will rename default as gaussian (hardware). Then there's no confusion. Should be short.

**Comment by fr500** [comment]
I was thinking, master should be identical to upstream, that way core changes can be pull requested to upstream.

Then have the hacks on top of master in a branch (ie, on every update, rebase + force push so the hacks are always on the tip of the branch)

Buildbot could build that branch with hacks then and you could have those runtime options, it would make it easier to rebase on the future and to push changes upstream.

**Comment by kps501** [comment]
I'll have to wait for someone to setup all that first and see what to do after the dust clears. That's way above my github level. :mrgreen:

**Comment by retro-wertz** [comment]
just trying give a point here (even it will not even matter at the end)...

there's a difference with a hack coz it gets in the way of gameplay or does not play at all like chrono triggers screen transition glitch and hacks that does changes hardware behaviour like how things sounded coz its 2018 and adding gazilion interp methods isnt just enough.

**Comment by fr500** [comment]
I think cores that have upstream support should have 2 branches generally speaking

- master - identical to upstream, used to bring up changes quickly
- libretro - stuff that's not mergeable to master, for instance sometimes upstream doesn't want to merge the build system, so libretro = master + build system changes, basically this branch is vanilla but it would suit our buildbot
- libretro-next / beetle, whatever you want to call them, which would include any hacks or enhancements that deviate for upstream

These simple changes would make updating easier, basically rebase such changes on top of master and force pushing would keep the changes on top and it would make it easy to keep up with upstream changes.

Small changes to the workflow could result in something a lot better than this:

image

**Comment by kps501** [comment]
Alrighty, digesting the info.

master = 1:1 clone
-- libretro = nothing but basic essentials like buildbot
-- libretro-extra = all that extra crap we've been working on

Now for libretro-extra, we always want to make available the 'good stuff' that basically everyone can agree on.

upstream:
-- Hires blending option
-- Multi-Cart support
-- Hardware gaussian = real hardware snes w/ brr overflow glitch (you won't see this option)
-- Show layers, etc.
-- Up+Down
-- Rifle adjustment (because there is no in-game lightgun calibration)

downstream:
-- Chrono Trigger resolution hack
-- Kat's Run graphics hack
-- Little Magic boot hack
-- Lufia 2 credits hack
-- Fast interlace

All above will be left default on, for normal user experience. I'm assuming standard users still want to play with the show layers and sound channel options. Or hide them?

Now for power users, you get the rest of the -experimental- hidden stuff: cpu / sfx overclock, audio interpolation, randomization, flicker. Anything that is outside normal snes hardware behavior. How does this plan sound?
(note that I've added custom 4-tap, 8-tap table loading feature. 4096-point gaussian and sinc tables. Gaussian uses nocash math which is very close to snes curve. Can't honestly say either sounds better or cleaner but anyone can create their own tables now and I can be done with it)

**Comment by retro-wertz** [comment]
this is sounding more complicated that it really needs to be...."yes, lets
hide these coz people will neer understand whats this for..."

**Comment by kps501** [comment]
Mostly everything now hidden. Gaussian hardware still default. I'm going to cry if there's still more.

Examples of new custom-4, custom-8 tables:
http://s000.tinyupload.com/index.php?file_id=02821437861696059549

Put into your RA/System directory. To use snes_audio_custom4_normal.bin (close to hardware gaussian), rename to snes_audio_custom4.bin. Basically instead of 256 lerp points, we now have 4096. Maybe smoother curves.

**Comment by retro-wertz** [comment]
like what ive said.. suggestion really dont matter (why even bothered asking).. **shutting mouth now from further interactions*

**Comment by Ryunam** [comment]
From a purely end-user perspective, I am not sure about restricting things like Runahead and the Input Lag Fix to the libretro-extra variant. If I understand correctly, these two aspects are intended to yield benefits that don't seem to have any perceived unintended consequence or drawback and instead "fix" things for the libretro implementation (or in the case of Runahead make it possible to use a frontend feature appropriately). I would prefer those two aspects to be preserved in all version of the libretro code, not just the "extra" version. 
But that's just my two cents: either way, if this "extra" version gives clear instructions on how to easily activate all the bells and whistles without introducing regressions and is distributed through the Buildbot just like the vanilla version, I would be completely okay with it.

**Comment by Tatsuya79** [comment]
I'm not really in favour of the advanced menu option too.
I don't like that you need a restart to have the extra options and it will force people that made some core option overrides to modify all of them... for something that is debatable if it makes things easier or not.

**Comment by kps501** [comment]
For everyone's sake, I will close this so no more damage is done. I've managed to upset everyone from left - right side by overdoing it, not understanding requests, and fking the atmosphere.

Created too much trouble in just a few days. We lost an experienced member contributing here because of me. I'm proven not qualified to do any more libretro* pull requests. Sorry. Terrible ideas on making things better. Destroying.

**Comment by Ryunam** [comment]
Hey, honestly though this is a pity . You were implementing a lot of interesting and helpful updates to this core and it is just a shame to lose your contributions because of disagreements that most likely can be sorted out reasonably. I hope you can reconsider this.

**Comment by fr500** [comment]
Noone is Gonna ditch anything, I'm just proposing workflow changes

**Comment by kps501** [comment]
If someone else wants to brunt the responsibility of screwing up libretro, I could re-fork the code again on my own side. But I'm not touching main snes9x libretro fork again, because I can't make everyone happy.

There's people who love the customizations and others not mentioned here who dislike it to a skin cutting T, even memory randomization or overclocking or (special) hires blending or *cough* Little Magic hackfix. Upstream regressions are different issue. But things got added that doesn't exist in main core which has drawn some dragon fire, and I'm not good at navigating people.

It'd be better just cut down all the fat that got added to main snes9x port to keep it clean. And have another completely separate snes9x-2018 fork to separate the two further. Confusing even more. More work. But core downloader hides all the unpopular ones when I look for new systems.

But as history has shown over the last 5 pull requests, I'm terribly awful.

**Comment by Tatsuya79** [comment]
I appreciate a lot of things you did here and I don't think you're responsible for people over reacting on small things.

The input lag fix has been done upstream too, the code is different though, so perhaps we can bring that change in if that's really needed.
I saw Dwedit pushing some commits to upstream too so I'm not sure what's different on the savestate side.
...and I'm a bit clueless about git operations as well.

**Comment by Ryunam** [comment]
@kps501, for what it's worth, I think having more options is always worth it and beneficial for the user, provided that those changes do not introduce regressions relative to the original code. 

Nothing you have recently added to this core should go to waste and once again, as far as I'm personally concerned, having memory randomization, overclocking and all of the hackfixes you have implemented is just great. So I hope these disagreements are sorted out and you can resume your work as originally intended.

**Comment by kps501** [comment]
Going to experiment by forking upstream directly and making a new port that won't interfere with snes9x-libretro. New name and such. This of course will take awhile since advanced newbie skills have clueless bumbling in the dark moments.

Then libretro can purge itself of my evil code and anything worth backporting from downport can be hand-transferred over here.

**Comment by twinaphex** [comment]
My hope was that cores like this would become self governing instead of a guy like me top down just ramming through changes. Which is why i stayed relatively hands off here.

Since communication seems to have broken down and people are growing disillusioned and leaving, I want to try to fix the situation here and make some hard decisions on what we do and what we wont do in the core. That way, nobody can be blamed but me for these decisions.

Can anybody tell me what the remaining disagreements are still about? I will to the best of my ability then make my own judgment on what we should do and make some hard decisions so we can all move forward here.

**Comment by fr500** [comment]
I don't think there was anything wrong with your options. I'm actually trying to do what I said above.
Some people just want the unadulterated upstream core (I'm amongst them)

**Comment by twinaphex** [comment]
If radius wants to take the lead on this repo, that is fine with me too. I would want this project and all the repos we have to become more of a team effort anyway.

**Comment by twinaphex** [comment]
I also think that you should grow a bit thicker skin @kps501. It might not seem that way at first, but when people point out criticism, it is not because they dislike your code or your efforts. its because they are invested in this core and they want to make sure that their issues get addressed before we enter the point of no return. It would be worse to get no responses at all, that would mean nobody would care.

I think I speak for everybody here when I say everybody liked your commits, the only criticism is stuff they want to see rectified before stuff gets merged. You should take this as constructive feedback instead of thinking that your commits are not wanted.

**Comment by fr500** [comment]
I just think hacks have a place, having an upstream core helps spotting regressions and whatnot, and all of that can be achieved on a single repo by using branches.

I don't think anyone would be against having a simpler way to rebase upstream changes.

**Comment by fr500** [comment]
I started a fork here, I'll be cherry picking the changes one by one checking what should be upstream and what shouldn't

https://github.com/fr500/snes9x/tree/libretro

No ETA though (world cup and all)

**Pull request closed without merging**
