### PR TITLE
Overscan and aspect ratio core options

### PR DESCRIPTION
**Pull request by Monroe88**
Overscan is controlled by core option now instead of RETRO_ENVIRONMENT_GET_OVERSCAN.

Core reported aspect ratio can now be set to 8:7 PAR (like in higan) or 4:3 DAR.

Also, update geometry when options are changed.

### CODE REVIEW

**Comment by Alcaro** [comment]
Same comments here as -mercury.

>> \+ else if(!strcmp(var.value, "disabled"))
>> \+ else if(!strcmp(var.value, "4:3"))
> 
> No real need for elseif, just use else. If the frontend hands out values other than those two, it's broken, and let's just assume it's not.
>
>> \+ core_bind.penviron(RETRO_ENVIRONMENT_SET_GEOMETRY, &av_info);
>
> @twinaphex, is it safe to call this when not needed?
>
> Other than that, +1

**Comment by fr500** [comment]
Is this PR still valid? what's stopping us?

**Comment by Monroe88** [comment]
Looks like I need to rebase again.

**Comment by Monroe88** [comment]
OK it should merge now.

**Comment by fr500** [comment]
Ok, seems like a positive change, I'm all up for it, and @Alcaro seemed to mostly agree.
BTW netplay has made me think about this again... maybe the older method would be better but implemented differently, ie some environment that can give you information about overscan countermeasures so the frontend can perform the overscan cropping....

Something to consider in the future, I'll merge it.

https://github.com/libretro/RetroArch/issues/4516

**Comment by Monroe88** [comment]
A frontend crop option that allows cropping pixels from each side independently would be best, especially if it took effect immediately. That way, you could use overrides to specify exact amounts of cropping for each game or core. The old crop overscan option required a restart and few cores actually implemented it anyway.

**Comment by fr500** [comment]
@Monroe88 I actually think we should have video "knobs" in the frontend
Independent from shaders, so you can crop, mask and stretch.

It would be a lot better imho.

**Comment by AlexFolland** [comment]
This is a good change.  How I've been handling this until now is using a core override for Snes9x in general and a game override for games that use the full overscan area like Dragon Quest 5.  This should be a better solution.

**Pull request merged**
