### PR TITLE
Up to date core changes

### PR DESCRIPTION
**Pull request by bearoso**
I cherry-picked several compatibility changes that haven't been implemented into the libretro repository yet. LAGFIX is no longer necessary because we now break out at that time with SCAN_KEYS_FLAG.

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, cool. So latency has been measured to be comparable?

**Comment by bearoso** [comment]
It's the same thing, just using Snes9x's built in variable instead of an extra one.

**Comment by fr500** [comment]
Oh that's nice
I think we have all that in my fork?

https://github.com/fr500/snes9x

We're gonna be replacing this fork soon (I just have to backport macs rifle).

**Comment by bearoso** [comment]
Sorry, I just picked a few bug fixes from upstream master since things had stagnated a bit, and retroarch users didn’t have them. I know you were working on unification, but didn’t know you had another fork.

**Comment by fr500** [comment]
Yeah no big deal, I get it they were probably complaining about the top gear 3000 issue to you too :)

I'll try to finish it up this week

**Pull request merged**
