### PR TITLE
Add "Extreme" option to cycle overclock setting

### PR DESCRIPTION
**Pull request by Electricstar**
Adds an "Extreme" overclock setting that is the equivelent of running the SNES without a divided clock speed. May most likely completely eliminate slowdown in the most intensive SNES game, including Gradius III and Rudra no Hihou (During a few spell animations). May also allow the removal of slowdown in parts of the second and third routes of Star Fox that still have it even at 500% SuperFX speed and Max overclock setting. Can also allow double speed in Star Ocean (during battles), if desired. In general, games that run without crashing will have absolutely no slowdown, no matter the game.

This is a duplicate of a PR I made, taking the proper steps and precautions this time.

### CODE REVIEW

**Comment by Electricstar** [comment]
> Did you actually compile the core and test games thoroughly with that change?
> 
> I tested many values when I made the cycle overclocking changes and it seems too much and probably break every game.
> I think Gradius was always full speed with 2/3/2 but it's just about 2 spots in the whole game, not worth making yet another profile.
> Star Fox runs too fast with every oc options ON and I find it hard to believe it's not crashing at all.
> 
> No need to add more options just for a test.

I've compiled it now, and currently testing games. I'll give a text file containing full results once i'm done testing.

Star Fox doesn't crash, as far as I tested, and runs with absolutely no slowdown, which is great.

**Comment by Electricstar** [comment]
[test results.txt](https://github.com/libretro/snes9x/files/2751727/test.results.txt)
The test results are in! I hate that nearly every RPG was broken by it...

**Comment by fr500** [comment]
I don't think it's worthwhile merging something that breaks so many games.
Also this is supposed to be an upstream friendly fork and I don't see that being mergeable.

**Comment by hizzlekizzle** [comment]
Gonna close this for now. We can revisit later, if needed.

**Pull request closed without merging**
